### ISSUE TITLE
Can you provide the training code, please? Thank you.

### ISSUE THREAD

**Issue by xuxiong0214** [AdelaideAuto-IDLab/Februus#4]
I am researching your paper. Could you please provide the inpainting models for CIFAR-10 and GTSRB? Thank you.

**Comment by xuelinweiwxl** [comment]
Have you got the inpainting model? I am also searching for it.

**Comment by baogiadoan** [comment]
The inpainting model should be included in largefile.tar.gz

**Comment by xuelinweiwxl** [comment]
I want to train this inpainting model on another dataset, but found no training code in this repository. Could you please provide the training code and settings? Thanks@baogiadoan

**Comment by baogiadoan** [comment]
Hi @xuelinweiwxl, We use GAN-based inpainting from [this work](https://github.com/otenim/GLCIC-PyTorch). However, the inpainting model is generic; given the many better models available nowadays, you can use any inpainting model for your datasets.

**Comment by xuelinweiwxl** [comment]
Thank you, @baogiadoan. I will give it a try.
